# Simple 1D Array

In [32]:
import numpy as np
import tensorflow as tf
from pprint import pprint

sess = tf.InteractiveSessionactiveSession()

In [2]:
t = np.array([0.,1.,2.,3.,4.,5.,6.])

In [4]:
pprint(t)

array([0., 1., 2., 3., 4., 5., 6.])


In [10]:
print(t.ndim)

1


In [11]:
print(t.shape)

(7,)


In [9]:
print(t[0], t[1], t[-1])

0.0 1.0 6.0


In [12]:
print(t[2:5], t[4:-1])

[2. 3. 4.] [4. 5.]


In [13]:
print(t[:2], t[3:])

[0. 1.] [3. 4. 5. 6.]


# 2D Array

In [14]:
t = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [15]:
print(t.ndim)
print(t.shape)

2
(4, 3)


In [24]:
t = tf.constant([[[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]]])

In [25]:
tf.shape(t).eval()

ValueError: Cannot evaluate tensor using `eval()`: No default session is registered. Use `with sess.as_default()` or pass an explicit session to `eval(session=sess)`

# Shape, Rank, Axis

In [41]:
t = tf.constant([1,2,3,4])
tf.shape(t).eval()

array([4])

In [43]:
t = tf.constant([[1,2],[3,4]]) #angle bracket이 몇개있는지가 rank의 갯수.
tf.shape(t).eval()

array([2, 2])

In [45]:
t = tf.constant([[[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]]])
tf.shape(t).eval()

array([1, 2, 3, 4])

# Matmul VS multiply

In [46]:
matrix1 = tf.constant([[1.,2.],[3.,4.]])
matrix2 = tf.constant([[4.,5.],[6.,7.]])

In [49]:
print(tf.matmul(matrix1,matrix2).eval())

[[16. 19.]
 [36. 43.]]


# Reduce mean

In [50]:
tf.reduce_mean([1,2], axis = 0).eval()

1

In [51]:
x = [[1.,2.],[3.,4.]]

tf.reduce_mean(x).eval()

2.5

In [52]:
tf.reduce_mean(x, axis=0).eval()

array([2., 3.], dtype=float32)

In [53]:
tf.reduce_mean(x, axis=1).eval()

array([1.5, 3.5], dtype=float32)

In [54]:
tf.reduce_mean(x, axis=1).eval()

array([1.5, 3.5], dtype=float32)

# Reduce sum

In [55]:
x = [[1.,2.],[3.,4.]]

In [56]:
tf.reduce_sum(x).eval()

10.0

In [58]:
tf.reduce_sum(x, axis=0).eval()

array([4., 6.], dtype=float32)

In [59]:
tf.reduce_sum(x, axis=1).eval()

array([3., 7.], dtype=float32)

In [61]:
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval()

5.0

# Argmax

maximum의 위치를 구한다!

In [62]:
x = [[0,1,2],[2,1,0]]
tf.argmax(x, axis=0).eval()

array([1, 0, 0], dtype=int64)

In [64]:
tf.argmax(x, axis=1).eval()

array([2, 0], dtype=int64)

In [65]:
tf.argmax(x, axis=-1).eval()

array([2, 0], dtype=int64)

# Reshape

바꿔주는 함수. -1을 주면 알아서 바꿔준다. 

In [67]:
t = np.array([[[0,1,2],
               [3,4,5]],
              [[6,7,8],
              [9,10,11]]])

print(t.shape)

(2, 2, 3)


In [68]:
tf.reshape(t, shape=[-1,3]).eval()

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [69]:
tf.reshape(t, shape=[-1,1,3]).eval()

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

# Reshape(squeeze, expand)

In [70]:
tf.squeeze([[0],[1],[2]]).eval()

array([0, 1, 2])

In [71]:
tf.expand_dims([0,1,2],1).eval()

array([[0],
       [1],
       [2]])

# One Hot

In [76]:
# rank를 하나더 expand해준다. 
tf.one_hot([[0],[1],[2],[0]], depth=3).eval()

array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[1., 0., 0.]]], dtype=float32)

In [77]:
t = tf.one_hot([[0],[1],[2],[0]], depth=3).eval()
tf.reshape(t, shape=[-1,3]).eval()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

# Casting

integer로 바꾸는 것.

In [78]:
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval()

array([1, 2, 3, 4])

In [79]:
tf.cast([True, False, 1 == 1, 0 ==1], tf.int32).eval()

array([1, 0, 1, 0])

# Stack

In [80]:
x = [1,4]
y = [2,5]
z = [3,6]

In [81]:
tf.stack([x,y,z]).eval()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [84]:
tf.stack([x,y,z], axis = 1).eval()

array([[1, 2, 3],
       [4, 5, 6]])

# Ones and Zeros like

In [85]:
x = [[0,1,2], [2,1,0]]

tf.ones_like(x).eval()

array([[1, 1, 1],
       [1, 1, 1]])

In [86]:
tf.zeros_like(x).eval()

array([[0, 0, 0],
       [0, 0, 0]])

# Zip

In [87]:
for x,y in zip([1,2,3],[4,5,6]):
    print(x,y)

1 4
2 5
3 6
