# Training and Test datasets

반드시 dataset을 나누어야 한다. 

training dataset을 가지고 model을 학습시키고, test dataset을 가지고 model을 검증한다. 

In [16]:
import tensorflow as tf
import numpy as np

In [31]:
x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

# Evaluation our model using this test dataset
x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]

In [32]:
X = tf.placeholder("float", [None,3])
Y = tf.placeholder("float", [None,3])
W = tf.Variable(tf.random_normal([3,3]))
b = tf.Variable(tf.random_normal([3]))

In [33]:
hypothesis = tf.nn.softmax(tf.matmul(X,W) + b)
cost = tf.reduce_mean(-tf.reduce_mean(Y * tf.log(hypothesis), axis = 1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-10).minimize(cost)

In [34]:
prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y,1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

In [56]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer], feed_dict={X:x_data, Y:y_data})
        print(step, cost_val, W_val)
        
    print("Prediction:", sess.run(prediction, feed_dict={X:x_test}))
    
    print("Accuracy:", sess.run(accuracy, feed_dict={X:x_test, Y:y_test}))

0 4.427725 [[-0.62601453 -0.5922774   0.7711507 ]
 [ 1.2061373  -1.8325603  -0.51203835]
 [ 0.2706739  -2.4411628  -1.5255661 ]]
1 4.427725 [[-0.62601453 -0.5922774   0.7711507 ]
 [ 1.2061373  -1.8325603  -0.51203835]
 [ 0.2706739  -2.4411628  -1.5255661 ]]
2 4.427725 [[-0.62601453 -0.5922774   0.7711507 ]
 [ 1.2061373  -1.8325603  -0.51203835]
 [ 0.2706739  -2.4411628  -1.5255661 ]]
3 4.427725 [[-0.62601453 -0.5922774   0.7711507 ]
 [ 1.2061373  -1.8325603  -0.51203835]
 [ 0.2706739  -2.4411628  -1.5255661 ]]
4 4.427725 [[-0.62601453 -0.5922774   0.7711507 ]
 [ 1.2061373  -1.8325603  -0.51203835]
 [ 0.2706739  -2.4411628  -1.5255661 ]]
5 4.427725 [[-0.62601453 -0.5922774   0.7711507 ]
 [ 1.2061373  -1.8325603  -0.51203835]
 [ 0.2706739  -2.4411628  -1.5255661 ]]
6 4.427725 [[-0.62601453 -0.5922774   0.7711507 ]
 [ 1.2061373  -1.8325603  -0.51203835]
 [ 0.2706739  -2.4411628  -1.5255661 ]]
7 4.427725 [[-0.62601453 -0.5922774   0.7711507 ]
 [ 1.2061373  -1.8325603  -0.51203835]
 [ 0.270

164 4.427725 [[-0.62601453 -0.5922774   0.7711507 ]
 [ 1.2061373  -1.8325603  -0.51203835]
 [ 0.2706739  -2.4411628  -1.5255661 ]]
165 4.427725 [[-0.62601453 -0.5922774   0.7711507 ]
 [ 1.2061373  -1.8325603  -0.51203835]
 [ 0.2706739  -2.4411628  -1.5255661 ]]
166 4.427725 [[-0.62601453 -0.5922774   0.7711507 ]
 [ 1.2061373  -1.8325603  -0.51203835]
 [ 0.2706739  -2.4411628  -1.5255661 ]]
167 4.427725 [[-0.62601453 -0.5922774   0.7711507 ]
 [ 1.2061373  -1.8325603  -0.51203835]
 [ 0.2706739  -2.4411628  -1.5255661 ]]
168 4.427725 [[-0.62601453 -0.5922774   0.7711507 ]
 [ 1.2061373  -1.8325603  -0.51203835]
 [ 0.2706739  -2.4411628  -1.5255661 ]]
169 4.427725 [[-0.62601453 -0.5922774   0.7711507 ]
 [ 1.2061373  -1.8325603  -0.51203835]
 [ 0.2706739  -2.4411628  -1.5255661 ]]
170 4.427725 [[-0.62601453 -0.5922774   0.7711507 ]
 [ 1.2061373  -1.8325603  -0.51203835]
 [ 0.2706739  -2.4411628  -1.5255661 ]]
171 4.427725 [[-0.62601453 -0.5922774   0.7711507 ]
 [ 1.2061373  -1.8325603  -0.51

# Normalization

In [77]:
# Non-normalized data
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

In [59]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [60]:
X = tf.placeholder(tf.float32, shape=[None,4])
Y = tf.placeholder(tf.float32, shape=[None,1])
W = tf.Variable(tf.random_normal([4,1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

In [61]:
hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [64]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [65]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [66]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X:x_data, Y:y_data})
    print(step, "Cost: ", cost_val, "\n Prediction : \n", hy_val)

0 Cost:  353518100000.0 
 Prediction : 
 [[419983.62]
 [845436.9 ]
 [665081.6 ]
 [466228.2 ]
 [549469.75]
 [554097.  ]
 [507850.53]
 [646588.1 ]]
1 Cost:  3.884034e+26 
 Prediction : 
 [[-1.3901856e+13]
 [-2.7985864e+13]
 [-2.2015470e+13]
 [-1.5432727e+13]
 [-1.8188293e+13]
 [-1.8341381e+13]
 [-1.6810509e+13]
 [-2.1403120e+13]]
2 Cost:  inf 
 Prediction : 
 [[4.6079579e+20]
 [9.2762914e+20]
 [7.2973239e+20]
 [5.1153855e+20]
 [6.0287549e+20]
 [6.0794978e+20]
 [5.5720702e+20]
 [7.0943530e+20]]
3 Cost:  inf 
 Prediction : 
 [[-1.5273699e+28]
 [-3.0747522e+28]
 [-2.4187966e+28]
 [-1.6955636e+28]
 [-1.9983124e+28]
 [-2.0151318e+28]
 [-1.8469378e+28]
 [-2.3515192e+28]]
4 Cost:  inf 
 Prediction : 
 [[5.0626736e+35]
 [1.0191681e+36]
 [8.0174281e+35]
 [5.6201741e+35]
 [6.6236756e+35]
 [6.6794261e+35]
 [6.1219249e+35]
 [7.7944278e+35]]
5 Cost:  inf 
 Prediction : 
 [[-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]]
6 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 

185 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
186 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
187 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
188 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
189 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
190 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
191 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
192 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
193 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
194 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
195 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
196 Cost:  nan 
 Pred

342 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
343 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
344 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
345 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
346 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
347 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
348 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
349 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
350 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
351 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
352 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
353 Cost:  nan 
 Pred

528 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
529 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
530 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
531 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
532 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
533 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
534 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
535 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
536 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
537 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
538 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
539 Cost:  nan 
 Pred

 [nan]]
687 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
688 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
689 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
690 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
691 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
692 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
693 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
694 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
695 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
696 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
697 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
698 Cost:  na

819 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
820 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
821 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
822 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
823 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
824 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
825 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
826 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
827 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
828 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
829 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
830 Cost:  nan 
 Pred

952 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
953 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
954 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
955 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
956 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
957 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
958 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
959 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
960 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
961 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
962 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
963 Cost:  nan 
 Pred

1135 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1136 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1137 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1138 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1139 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1140 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1141 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1142 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1143 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1144 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1145 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1146 Cost:

1313 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1314 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1315 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1316 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1317 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1318 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1319 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1320 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1321 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1322 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1323 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1324 Cost:

1483 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1484 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1485 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1486 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1487 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1488 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1489 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1490 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1491 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1492 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1493 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1494 Cost:

1653 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1654 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1655 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1656 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1657 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1658 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1659 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1660 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1661 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1662 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1663 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1664 Cost:

1825 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1826 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1827 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1828 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1829 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1830 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1831 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1832 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1833 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1834 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1835 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1836 Cost:

1951 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1952 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1953 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1954 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1955 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1956 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1957 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1958 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1959 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1960 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1961 Cost:  nan 
 Prediction : 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1962 Cost:

### Normalized inputs(min-max scale)

In [93]:
def min_max_scaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data,0) - np.min(data,0)
    
    return numerator / (denominator + 1e-7)

In [94]:
xy_1 = min_max_scaler(xy)

In [80]:
from sklearn.preprocessing import MinMaxScaler

In [84]:
xy_2 = MinMaxScaler().fit_transform(xy)

In [95]:
x_data = xy_1[:, 0:-1]
y_data = xy_1[:, [-1]]

In [96]:
X = tf.placeholder(tf.float32, shape=[None,4])
Y = tf.placeholder(tf.float32, shape=[None,1])
W = tf.Variable(tf.random_normal([4,1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

In [97]:
hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [98]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [99]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [100]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X:x_data, Y:y_data})
    print(step, "Cost: ", cost_val, "\n Prediction : \n", hy_val)

0 Cost:  3.088748 
 Prediction : 
 [[1.3779094]
 [3.0373638]
 [2.4636183]
 [1.8170778]
 [2.0693   ]
 [2.0278118]
 [2.057107 ]
 [2.453218 ]]
1 Cost:  3.0885625 
 Prediction : 
 [[1.3778368]
 [3.0372875]
 [2.4635544]
 [1.8170282]
 [2.0692418]
 [2.0277553]
 [2.057066 ]
 [2.453176 ]]
2 Cost:  3.0883775 
 Prediction : 
 [[1.3777642]
 [3.0372112]
 [2.4634907]
 [1.8169786]
 [2.0691838]
 [2.0276988]
 [2.057025 ]
 [2.4531338]]
3 Cost:  3.0881925 
 Prediction : 
 [[1.3776915]
 [3.037135 ]
 [2.4634268]
 [1.8169289]
 [2.069126 ]
 [2.0276425]
 [2.056984 ]
 [2.4530916]]
4 Cost:  3.088007 
 Prediction : 
 [[1.3776189]
 [3.0370586]
 [2.4633632]
 [1.8168793]
 [2.0690677]
 [2.027586 ]
 [2.056943 ]
 [2.4530497]]
5 Cost:  3.087822 
 Prediction : 
 [[1.3775463]
 [3.0369823]
 [2.4632993]
 [1.8168297]
 [2.0690098]
 [2.0275295]
 [2.0569022]
 [2.4530075]]
6 Cost:  3.087637 
 Prediction : 
 [[1.3774737]
 [3.0369058]
 [2.4632359]
 [1.81678  ]
 [2.0689516]
 [2.027473 ]
 [2.0568612]
 [2.4529653]]
7 Cost:  3.087452

 [[1.3650913]
 [3.023886 ]
 [2.4523606]
 [1.808318 ]
 [2.0590563]
 [2.0178473]
 [2.0498772]
 [2.445775 ]]
178 Cost:  3.0559764 
 Prediction : 
 [[1.3650193]
 [3.0238101]
 [2.4522972]
 [1.8082688]
 [2.0589986]
 [2.0177913]
 [2.0498364]
 [2.445733 ]]
179 Cost:  3.0557938 
 Prediction : 
 [[1.3649473]
 [3.0237343]
 [2.4522338]
 [1.8082196]
 [2.0589411]
 [2.0177352]
 [2.0497959]
 [2.445691 ]]
180 Cost:  3.055611 
 Prediction : 
 [[1.3648752]
 [3.0236583]
 [2.4521704]
 [1.8081703]
 [2.0588834]
 [2.017679 ]
 [2.049755 ]
 [2.4456491]]
181 Cost:  3.0554285 
 Prediction : 
 [[1.3648031]
 [3.0235825]
 [2.4521072]
 [1.808121 ]
 [2.058826 ]
 [2.017623 ]
 [2.0497146]
 [2.4456074]]
182 Cost:  3.055246 
 Prediction : 
 [[1.3647311]
 [3.0235069]
 [2.452044 ]
 [1.8080717]
 [2.0587683]
 [2.017567 ]
 [2.049674 ]
 [2.4455657]]
183 Cost:  3.0550632 
 Prediction : 
 [[1.3646591]
 [3.023431 ]
 [2.4519806]
 [1.8080225]
 [2.0587106]
 [2.0175111]
 [2.0496333]
 [2.4455237]]
184 Cost:  3.054881 
 Prediction : 
 [

290 Cost:  3.0355906 
 Prediction : 
 [[1.3569579]
 [3.0153356]
 [2.4452174]
 [1.8027582]
 [2.0525558]
 [2.0115237]
 [2.0452876]
 [2.4410505]]
291 Cost:  3.0354095 
 Prediction : 
 [[1.3568861]
 [3.0152602]
 [2.4451542]
 [1.8027091]
 [2.0524983]
 [2.011468 ]
 [2.045247 ]
 [2.4410088]]
292 Cost:  3.0352283 
 Prediction : 
 [[1.3568144]
 [3.0151846]
 [2.4450912]
 [1.8026601]
 [2.0524411]
 [2.0114121]
 [2.0452065]
 [2.440967 ]]
293 Cost:  3.0350475 
 Prediction : 
 [[1.3567426]
 [3.015109 ]
 [2.4450283]
 [1.8026111]
 [2.052384 ]
 [2.0113564]
 [2.0451663]
 [2.4409256]]
294 Cost:  3.0348663 
 Prediction : 
 [[1.3566709]
 [3.0150337]
 [2.4449651]
 [1.802562 ]
 [2.0523264]
 [2.0113006]
 [2.0451257]
 [2.4408839]]
295 Cost:  3.0346854 
 Prediction : 
 [[1.3565991]
 [3.0149584]
 [2.4449022]
 [1.8025129]
 [2.052269 ]
 [2.0112448]
 [2.0450852]
 [2.4408422]]
296 Cost:  3.034504 
 Prediction : 
 [[1.3565273]
 [3.0148828]
 [2.444839 ]
 [1.8024639]
 [2.0522118]
 [2.011189 ]
 [2.0450447]
 [2.4408004]]


414 Cost:  3.0132089 
 Prediction : 
 [[1.3480754]
 [3.0059886]
 [2.4374104]
 [1.7966837]
 [2.0454528]
 [2.0046139]
 [2.0402713]
 [2.435884 ]]
415 Cost:  3.0130296 
 Prediction : 
 [[1.3480039]
 [3.0059133]
 [2.4373474]
 [1.7966348]
 [2.0453956]
 [2.0045583]
 [2.040231 ]
 [2.4358425]]
416 Cost:  3.0128498 
 Prediction : 
 [[1.3479323]
 [3.005838 ]
 [2.4372845]
 [1.7965859]
 [2.0453384]
 [2.0045028]
 [2.0401907]
 [2.435801 ]]
417 Cost:  3.0126696 
 Prediction : 
 [[1.3478609]
 [3.0057628]
 [2.4372215]
 [1.796537 ]
 [2.0452812]
 [2.004447 ]
 [2.0401502]
 [2.4357593]]
418 Cost:  3.0124905 
 Prediction : 
 [[1.3477895]
 [3.0056877]
 [2.4371588]
 [1.7964882]
 [2.0452242]
 [2.0043914]
 [2.0401099]
 [2.4357178]]
419 Cost:  3.0123105 
 Prediction : 
 [[1.347718 ]
 [3.0056124]
 [2.437096 ]
 [1.7964393]
 [2.045167 ]
 [2.0043359]
 [2.0400696]
 [2.435676 ]]
420 Cost:  3.012131 
 Prediction : 
 [[1.3476465]
 [3.005537 ]
 [2.4370332]
 [1.7963904]
 [2.0451097]
 [2.00428  ]
 [2.0400293]
 [2.4356346]]


610 Cost:  2.9782553 
 Prediction : 
 [[1.3341254]
 [2.9913082]
 [2.4251466]
 [1.7871392]
 [2.0342941]
 [1.9937584]
 [2.0323873]
 [2.427764 ]]
611 Cost:  2.9780784 
 Prediction : 
 [[1.3340545]
 [2.9912336]
 [2.4250844]
 [1.7870908]
 [2.0342376]
 [1.9937032]
 [2.0323472]
 [2.4277225]]
612 Cost:  2.9779015 
 Prediction : 
 [[1.3339837]
 [2.991159 ]
 [2.425022 ]
 [1.7870423]
 [2.0341809]
 [1.993648 ]
 [2.0323071]
 [2.4276812]]
613 Cost:  2.9777246 
 Prediction : 
 [[1.3339128]
 [2.9910843]
 [2.4249597]
 [1.7869937]
 [2.0341241]
 [1.993593 ]
 [2.032267 ]
 [2.42764  ]]
614 Cost:  2.9775476 
 Prediction : 
 [[1.3338419]
 [2.9910097]
 [2.4248972]
 [1.7869453]
 [2.0340674]
 [1.9935378]
 [2.032227 ]
 [2.4275987]]
615 Cost:  2.9773705 
 Prediction : 
 [[1.333771 ]
 [2.990935 ]
 [2.424835 ]
 [1.7868968]
 [2.0340106]
 [1.9934826]
 [2.032187 ]
 [2.4275575]]
616 Cost:  2.9771938 
 Prediction : 
 [[1.3337002]
 [2.9908605]
 [2.4247727]
 [1.7868483]
 [2.0339541]
 [1.9934275]
 [2.032147 ]
 [2.4275162]]

757 Cost:  2.9523716 
 Prediction : 
 [[1.3237364]
 [2.9803672]
 [2.4160078]
 [1.7800279]
 [2.02598  ]
 [1.9856696]
 [2.0265102]
 [2.4217086]]
758 Cost:  2.952197 
 Prediction : 
 [[1.3236661]
 [2.9802933]
 [2.4159458]
 [1.7799796]
 [2.0259237]
 [1.9856148]
 [2.0264704]
 [2.4216676]]
759 Cost:  2.952022 
 Prediction : 
 [[1.3235956]
 [2.980219 ]
 [2.415884 ]
 [1.7799314]
 [2.0258672]
 [1.9855599]
 [2.0264306]
 [2.4216266]]
760 Cost:  2.9518468 
 Prediction : 
 [[1.3235252]
 [2.9801447]
 [2.415822 ]
 [1.7798831]
 [2.025811 ]
 [1.9855051]
 [2.0263906]
 [2.4215853]]
761 Cost:  2.9516718 
 Prediction : 
 [[1.3234549]
 [2.9800706]
 [2.41576  ]
 [1.7798349]
 [2.0257545]
 [1.9854503]
 [2.0263507]
 [2.4215443]]
762 Cost:  2.9514966 
 Prediction : 
 [[1.3233844]
 [2.9799964]
 [2.415698 ]
 [1.7797866]
 [2.0256982]
 [1.9853954]
 [2.026311 ]
 [2.421503 ]]
763 Cost:  2.9513216 
 Prediction : 
 [[1.323314 ]
 [2.9799223]
 [2.415636 ]
 [1.7797384]
 [2.0256417]
 [1.9853406]
 [2.026271 ]
 [2.421462 ]]
7

882 Cost:  2.9305859 
 Prediction : 
 [[1.3149515]
 [2.9711137]
 [2.4082775]
 [1.7740115]
 [2.0189471]
 [1.9788271]
 [2.0215366]
 [2.4165835]]
883 Cost:  2.9304123 
 Prediction : 
 [[1.3148813]
 [2.9710398]
 [2.4082158]
 [1.7739633]
 [2.0188909]
 [1.9787725]
 [2.021497 ]
 [2.4165428]]
884 Cost:  2.9302385 
 Prediction : 
 [[1.3148112]
 [2.9709659]
 [2.408154 ]
 [1.7739153]
 [2.0188346]
 [1.9787179]
 [2.0214572]
 [2.4165018]]
885 Cost:  2.9300647 
 Prediction : 
 [[1.3147411]
 [2.970892 ]
 [2.4080923]
 [1.7738672]
 [2.0187786]
 [1.9786632]
 [2.0214174]
 [2.4164608]]
886 Cost:  2.9298913 
 Prediction : 
 [[1.314671 ]
 [2.970818 ]
 [2.4080305]
 [1.7738192]
 [2.0187223]
 [1.9786086]
 [2.0213778]
 [2.41642  ]]
887 Cost:  2.9297178 
 Prediction : 
 [[1.314601 ]
 [2.9707441]
 [2.4079688]
 [1.7737712]
 [2.0186663]
 [1.9785539]
 [2.021338 ]
 [2.416379 ]]
888 Cost:  2.9295442 
 Prediction : 
 [[1.3145308]
 [2.9706702]
 [2.407907 ]
 [1.7737231]
 [2.01861  ]
 [1.9784993]
 [2.0212982]
 [2.416338 ]]

1062 Cost:  2.8995667 
 Prediction : 
 [[1.3023794]
 [2.9578638]
 [2.3972092]
 [1.7653979]
 [2.0088782]
 [1.9690306]
 [2.0144136]
 [2.4092417]]
1063 Cost:  2.8993957 
 Prediction : 
 [[1.3023098]
 [2.9577904]
 [2.3971481]
 [1.7653502]
 [2.0088224]
 [1.9689764]
 [2.0143743]
 [2.4092011]]
1064 Cost:  2.8992243 
 Prediction : 
 [[1.3022401]
 [2.957717 ]
 [2.3970869]
 [1.7653025]
 [2.0087667]
 [1.9689221]
 [2.0143347]
 [2.4091606]]
1065 Cost:  2.899053 
 Prediction : 
 [[1.3021705]
 [2.9576435]
 [2.3970256]
 [1.7652549]
 [2.0087109]
 [1.9688679]
 [2.0142953]
 [2.4091198]]
1066 Cost:  2.8988822 
 Prediction : 
 [[1.302101 ]
 [2.9575703]
 [2.3969643]
 [1.7652072]
 [2.008655 ]
 [1.9688137]
 [2.014256 ]
 [2.4090793]]
1067 Cost:  2.8987112 
 Prediction : 
 [[1.3020315]
 [2.9574971]
 [2.396903 ]
 [1.7651595]
 [2.0085995]
 [1.9687595]
 [2.0142164]
 [2.4090385]]
1068 Cost:  2.8985403 
 Prediction : 
 [[1.3019619]
 [2.9574237]
 [2.3968418]
 [1.7651118]
 [2.0085437]
 [1.9687053]
 [2.014177 ]
 [2.408

1247 Cost:  2.8681092 
 Prediction : 
 [[1.2895539]
 [2.944336 ]
 [2.3859096]
 [1.7566048]
 [1.9985998]
 [1.9590297]
 [2.0071383]
 [2.4017398]]
1248 Cost:  2.8679407 
 Prediction : 
 [[1.2894847]
 [2.944263 ]
 [2.385849 ]
 [1.7565575]
 [1.9985445]
 [1.9589759]
 [2.0070992]
 [2.4016995]]
1249 Cost:  2.867772 
 Prediction : 
 [[1.2894158]
 [2.9441905]
 [2.385788 ]
 [1.7565101]
 [1.9984891]
 [1.9589221]
 [2.00706  ]
 [2.4016593]]
1250 Cost:  2.8676033 
 Prediction : 
 [[1.2893467]
 [2.9441175]
 [2.3857274]
 [1.7564628]
 [1.9984338]
 [1.9588683]
 [2.007021 ]
 [2.401619 ]]
1251 Cost:  2.867435 
 Prediction : 
 [[1.2892778]
 [2.944045 ]
 [2.3856666]
 [1.7564155]
 [1.9983785]
 [1.9588145]
 [2.0069816]
 [2.4015784]]
1252 Cost:  2.8672662 
 Prediction : 
 [[1.2892087]
 [2.943972 ]
 [2.3856058]
 [1.7563682]
 [1.9983232]
 [1.9587607]
 [2.0069425]
 [2.4015381]]
1253 Cost:  2.8670976 
 Prediction : 
 [[1.2891397]
 [2.9438994]
 [2.385545 ]
 [1.756321 ]
 [1.9982679]
 [1.9587069]
 [2.0069034]
 [2.4014

 [2.3980293]]
1340 Cost:  2.8524656 
 Prediction : 
 [[1.2831428]
 [2.9375763]
 [2.380262 ]
 [1.752208 ]
 [1.9934616]
 [1.9540303]
 [2.0034997]
 [2.397989 ]]
1341 Cost:  2.8522975 
 Prediction : 
 [[1.2830739]
 [2.9375033]
 [2.3802013]
 [1.7521608]
 [1.9934063]
 [1.9539765]
 [2.0034606]
 [2.3979487]]
1342 Cost:  2.85213 
 Prediction : 
 [[1.2830051]
 [2.9374309]
 [2.3801405]
 [1.7521136]
 [1.9933512]
 [1.9539227]
 [2.0034215]
 [2.3979082]]
1343 Cost:  2.8519616 
 Prediction : 
 [[1.2829362]
 [2.9373581]
 [2.3800797]
 [1.7520663]
 [1.9932959]
 [1.9538691]
 [2.0033824]
 [2.397868 ]]
1344 Cost:  2.8517942 
 Prediction : 
 [[1.2828674]
 [2.9372857]
 [2.3800192]
 [1.7520192]
 [1.9932408]
 [1.9538155]
 [2.0033433]
 [2.3978276]]
1345 Cost:  2.8516269 
 Prediction : 
 [[1.2827988]
 [2.937213 ]
 [2.3799586]
 [1.7519721]
 [1.9931858]
 [1.9537618]
 [2.0033045]
 [2.3977876]]
1346 Cost:  2.8514595 
 Prediction : 
 [[1.28273  ]
 [2.9371405]
 [2.379898 ]
 [1.751925 ]
 [1.9931307]
 [1.9537082]
 [2.003

 [2.395214 ]]
1410 Cost:  2.840763 
 Prediction : 
 [[1.2783346]
 [2.9325027]
 [2.3760242]
 [1.7489102]
 [1.9896069]
 [1.9502795]
 [2.0007703]
 [2.395174 ]]
1411 Cost:  2.8405962 
 Prediction : 
 [[1.2782661]
 [2.9324303]
 [2.3759637]
 [1.7488631]
 [1.9895519]
 [1.9502261]
 [2.0007312]
 [2.3951337]]
1412 Cost:  2.8404293 
 Prediction : 
 [[1.2781975]
 [2.9323578]
 [2.3759031]
 [1.748816 ]
 [1.9894968]
 [1.9501724]
 [2.0006924]
 [2.3950934]]
1413 Cost:  2.8402624 
 Prediction : 
 [[1.2781289]
 [2.9322855]
 [2.3758426]
 [1.748769 ]
 [1.9894419]
 [1.950119 ]
 [2.0006533]
 [2.3950534]]
1414 Cost:  2.840096 
 Prediction : 
 [[1.2780604]
 [2.9322133]
 [2.375782 ]
 [1.748722 ]
 [1.9893868]
 [1.9500654]
 [2.0006144]
 [2.395013 ]]
1415 Cost:  2.839929 
 Prediction : 
 [[1.2779918]
 [2.9321408]
 [2.3757217]
 [1.7486749]
 [1.989332 ]
 [1.950012 ]
 [2.0005753]
 [2.3949728]]
1416 Cost:  2.8397624 
 Prediction : 
 [[1.2779231]
 [2.9320683]
 [2.3756614]
 [1.7486278]
 [1.9892769]
 [1.9499583]
 [2.0005

1537 Cost:  2.8196757 
 Prediction : 
 [[1.2696447]
 [2.923328 ]
 [2.3683605]
 [1.7429466]
 [1.9826367]
 [1.9434971]
 [1.9958322]
 [2.3900795]]
1538 Cost:  2.8195105 
 Prediction : 
 [[1.2695765]
 [2.923256 ]
 [2.3683004]
 [1.7428997]
 [1.982582 ]
 [1.9434438]
 [1.9957933]
 [2.3900394]]
1539 Cost:  2.819345 
 Prediction : 
 [[1.2695081]
 [2.923184 ]
 [2.36824  ]
 [1.7428528]
 [1.9825273]
 [1.9433905]
 [1.9957545]
 [2.3899996]]
1540 Cost:  2.81918 
 Prediction : 
 [[1.2694399]
 [2.923112 ]
 [2.3681798]
 [1.742806 ]
 [1.9824724]
 [1.9433372]
 [1.9957156]
 [2.3899596]]
1541 Cost:  2.8190145 
 Prediction : 
 [[1.2693716]
 [2.92304  ]
 [2.3681197]
 [1.7427591]
 [1.9824177]
 [1.9432839]
 [1.9956769]
 [2.3899195]]
1542 Cost:  2.8188496 
 Prediction : 
 [[1.2693033]
 [2.922968 ]
 [2.3680596]
 [1.7427123]
 [1.982363 ]
 [1.9432306]
 [1.9956381]
 [2.3898795]]
1543 Cost:  2.818684 
 Prediction : 
 [[1.2692351]
 [2.922896 ]
 [2.3679993]
 [1.7426653]
 [1.9823083]
 [1.9431773]
 [1.9955993]
 [2.389839

1667 Cost:  2.7983003 
 Prediction : 
 [[1.2607948]
 [2.9139862]
 [2.360556 ]
 [1.7368714]
 [1.9755375]
 [1.9365889]
 [1.9908007]
 [2.3848898]]
1668 Cost:  2.7981367 
 Prediction : 
 [[1.2607268]
 [2.9139147]
 [2.360496 ]
 [1.7368246]
 [1.975483 ]
 [1.9365357]
 [1.990762 ]
 [2.38485  ]]
1669 Cost:  2.7979727 
 Prediction : 
 [[1.2606587]
 [2.9138427]
 [2.360436 ]
 [1.736778 ]
 [1.9754283]
 [1.9364827]
 [1.9907234]
 [2.38481  ]]
1670 Cost:  2.7978086 
 Prediction : 
 [[1.2605908]
 [2.913771 ]
 [2.3603761]
 [1.7367313]
 [1.9753739]
 [1.9364296]
 [1.9906847]
 [2.3847702]]
1671 Cost:  2.797645 
 Prediction : 
 [[1.2605228]
 [2.9136992]
 [2.360316 ]
 [1.7366846]
 [1.9753193]
 [1.9363766]
 [1.9906461]
 [2.3847303]]
1672 Cost:  2.797481 
 Prediction : 
 [[1.2604549]
 [2.9136274]
 [2.3602562]
 [1.736638 ]
 [1.9752648]
 [1.9363234]
 [1.9906074]
 [2.3846903]]
1673 Cost:  2.7973177 
 Prediction : 
 [[1.260387 ]
 [2.9135556]
 [2.360196 ]
 [1.7365913]
 [1.9752103]
 [1.9362705]
 [1.9905689]
 [2.3846

1781 Cost:  2.7797184 
 Prediction : 
 [[1.2530732]
 [2.9058266]
 [2.3537407]
 [1.7315682]
 [1.9693396]
 [1.9305575]
 [1.986407 ]
 [2.380355 ]]
1782 Cost:  2.7795558 
 Prediction : 
 [[1.2530055]
 [2.905755 ]
 [2.3536808]
 [1.7315217]
 [1.9692852]
 [1.9305046]
 [1.9863684]
 [2.3803153]]
1783 Cost:  2.7793937 
 Prediction : 
 [[1.252938 ]
 [2.9056835]
 [2.3536212]
 [1.7314754]
 [1.9692311]
 [1.9304519]
 [1.98633  ]
 [2.3802757]]
1784 Cost:  2.7792318 
 Prediction : 
 [[1.2528706]
 [2.9056125]
 [2.3535619]
 [1.7314291]
 [1.9691769]
 [1.9303992]
 [1.9862916]
 [2.380236 ]]
1785 Cost:  2.7790694 
 Prediction : 
 [[1.2528031]
 [2.905541 ]
 [2.353502 ]
 [1.7313827]
 [1.9691228]
 [1.9303465]
 [1.9862533]
 [2.3801963]]
1786 Cost:  2.778907 
 Prediction : 
 [[1.2527355]
 [2.9054697]
 [2.3534424]
 [1.7313364]
 [1.9690685]
 [1.9302937]
 [1.9862149]
 [2.3801565]]
1787 Cost:  2.7787454 
 Prediction : 
 [[1.2526679]
 [2.9053984]
 [2.353383 ]
 [1.73129  ]
 [1.9690144]
 [1.930241 ]
 [1.9861765]
 [2.380

1890 Cost:  2.7621105 
 Prediction : 
 [[1.2457249]
 [2.8980658]
 [2.3472567]
 [1.7265205]
 [1.9634418]
 [1.924818 ]
 [1.9822245]
 [2.3760397]]
1891 Cost:  2.761949 
 Prediction : 
 [[1.2456577]
 [2.8979948]
 [2.347197 ]
 [1.7264743]
 [1.9633877]
 [1.9247655]
 [1.9821861]
 [2.376    ]]
1892 Cost:  2.7617881 
 Prediction : 
 [[1.2455904]
 [2.8979235]
 [2.3471377]
 [1.726428 ]
 [1.9633336]
 [1.9247129]
 [1.9821477]
 [2.3759604]]
1893 Cost:  2.7616272 
 Prediction : 
 [[1.245523 ]
 [2.8978524]
 [2.3470783]
 [1.7263818]
 [1.9632796]
 [1.9246602]
 [1.9821093]
 [2.3759208]]
1894 Cost:  2.761466 
 Prediction : 
 [[1.2454557]
 [2.8977814]
 [2.347019 ]
 [1.7263354]
 [1.9632256]
 [1.9246076]
 [1.982071 ]
 [2.3758812]]
1895 Cost:  2.7613056 
 Prediction : 
 [[1.2453885]
 [2.8977103]
 [2.3469596]
 [1.7262893]
 [1.9631716]
 [1.9245552]
 [1.9820328]
 [2.3758419]]
1896 Cost:  2.7611449 
 Prediction : 
 [[1.2453213]
 [2.8976393]
 [2.3469002]
 [1.7262431]
 [1.9631176]
 [1.9245026]
 [1.9819945]
 [2.3758