# Loading data from file

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.set_random_seed(777)

In [3]:
xy = np.loadtxt("data-01-test-score.csv", delimiter=',')

In [8]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [12]:
print(x_data.shape, len(x_data))
print(y_data.shape, len(y_data))

(25, 3) 25
(25, 1) 25


In [13]:
X = tf.placeholder(tf.float32, shape=[None,3])
Y = tf.placeholder(tf.float32, shape=[None,1])

In [16]:
W = tf.Variable(tf.random_normal([3,1]), name='Weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

In [17]:
hypothesis = tf.matmul(X,W) + b

In [18]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [19]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

In [27]:
sess = tf.Session()

sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict = {X:x_data, Y:y_data})
    
    print(step, "Cost : ", cost_val, "\n Prediction : \n", hy_val)

0 Cost :  38475.113 
 Prediction : 
 [[-32.92256 ]
 [-36.308025]
 [-37.548553]
 [-38.93094 ]
 [-28.650436]
 [-18.012749]
 [-27.368713]
 [-17.838268]
 [-30.93406 ]
 [-24.226639]
 [-27.41531 ]
 [-24.93708 ]
 [-40.661682]
 [-36.430157]
 [-26.815094]
 [-35.310772]
 [-36.06806 ]
 [-32.226337]
 [-39.58057 ]
 [-35.48207 ]
 [-32.200455]
 [-32.449986]
 [-31.539673]
 [-37.598213]
 [-38.989185]]
1 Cost :  14230.165 
 Prediction : 
 [[39.357628]
 [50.565224]
 [48.049553]
 [54.29155 ]
 [37.60464 ]
 [30.833788]
 [42.411312]
 [33.892056]
 [50.25456 ]
 [50.972942]
 [39.81423 ]
 [41.352146]
 [47.773327]
 [37.085663]
 [43.285515]
 [52.8449  ]
 [33.94624 ]
 [51.516502]
 [44.729755]
 [39.9556  ]
 [49.627693]
 [49.0485  ]
 [46.4772  ]
 [35.278255]
 [51.045197]]
2 Cost :  5266.1357 
 Prediction : 
 [[ 83.30801 ]
 [103.38862 ]
 [100.09779 ]
 [110.97572 ]
 [ 77.891106]
 [ 60.534775]
 [ 84.841194]
 [ 65.34674 ]
 [ 99.621185]
 [ 96.69768 ]
 [ 80.693275]
 [ 81.659225]
 [101.54665 ]
 [ 81.78743 ]
 [ 85.910255]
 [

140 Cost :  7.500273 
 Prediction : 
 [[151.57031]
 [185.3014 ]
 [180.87881]
 [198.9173 ]
 [140.35901]
 [106.5201 ]
 [150.65337]
 [114.11859]
 [176.10092]
 [167.44705]
 [144.09653]
 [144.10435]
 [185.03824]
 [151.23463]
 [152.0013 ]
 [189.54897]
 [142.65982]
 [181.42607]
 [175.61835]
 [157.07767]
 [176.5522 ]
 [175.42303]
 [167.5111 ]
 [148.49501]
 [190.72125]]
141 Cost :  7.498954 
 Prediction : 
 [[151.57086 ]
 [185.30115 ]
 [180.87907 ]
 [198.91731 ]
 [140.3588  ]
 [106.51946 ]
 [150.65327 ]
 [114.118416]
 [176.10016 ]
 [167.44574 ]
 [144.09644 ]
 [144.10374 ]
 [185.03873 ]
 [151.23534 ]
 [152.00105 ]
 [189.54855 ]
 [142.66049 ]
 [181.42603 ]
 [175.61899 ]
 [157.0783  ]
 [176.55206 ]
 [175.42262 ]
 [167.51111 ]
 [148.49614 ]
 [190.72125 ]]
142 Cost :  7.497613 
 Prediction : 
 [[151.57143]
 [185.30089]
 [180.8793 ]
 [198.91731]
 [140.35857]
 [106.51881]
 [150.65318]
 [114.11823]
 [176.0994 ]
 [167.44438]
 [144.0963 ]
 [144.10312]
 [185.0392 ]
 [151.23602]
 [152.00078]
 [189.54814]
 

262 Cost :  7.3462195 
 Prediction : 
 [[151.63739 ]
 [185.27144 ]
 [180.9087  ]
 [198.92064 ]
 [140.33272 ]
 [106.44268 ]
 [150.64345 ]
 [114.097145]
 [176.01155 ]
 [167.28981 ]
 [144.08398 ]
 [144.03197 ]
 [185.09706 ]
 [151.31781 ]
 [151.97157 ]
 [189.50096 ]
 [142.74013 ]
 [181.4214  ]
 [175.69609 ]
 [157.15388 ]
 [176.53511 ]
 [175.3735  ]
 [167.5125  ]
 [148.62823 ]
 [190.72131 ]]
263 Cost :  7.345039 
 Prediction : 
 [[151.63792]
 [185.2712 ]
 [180.90894]
 [198.92067]
 [140.33249]
 [106.44206]
 [150.64336]
 [114.09698]
 [176.01083]
 [167.28854]
 [144.08388]
 [144.03137]
 [185.09752]
 [151.31845]
 [151.97133]
 [189.50056]
 [142.74075]
 [181.42136]
 [175.69672]
 [157.15448]
 [176.53497]
 [175.3731 ]
 [167.51248]
 [148.62929]
 [190.72131]]
264 Cost :  7.343827 
 Prediction : 
 [[151.63846]
 [185.27097]
 [180.90918]
 [198.92068]
 [140.3323 ]
 [106.44145]
 [150.64328]
 [114.09681]
 [176.01013]
 [167.2873 ]
 [144.08377]
 [144.03079]
 [185.09799]
 [151.31912]
 [151.9711 ]
 [189.50018]


396 Cost :  7.1951323 
 Prediction : 
 [[151.7071 ]
 [185.24023]
 [180.93971]
 [198.92416]
 [140.30527]
 [106.36225]
 [150.63329]
 [114.07516]
 [175.9187 ]
 [167.12659]
 [144.07098]
 [143.95677]
 [185.15805]
 [151.40399]
 [151.94084]
 [189.45108]
 [142.82326]
 [181.4168 ]
 [175.77676]
 [157.233  ]
 [176.51749]
 [175.32204]
 [167.51407]
 [148.76646]
 [190.72128]]
397 Cost :  7.19406 
 Prediction : 
 [[151.70761]
 [185.24002]
 [180.93994]
 [198.9242 ]
 [140.30507]
 [106.36166]
 [150.63321]
 [114.075  ]
 [175.91805]
 [167.12543]
 [144.07089]
 [143.95624]
 [185.15851]
 [151.40463]
 [151.94061]
 [189.45073]
 [142.82387]
 [181.41678]
 [175.77736]
 [157.23358]
 [176.51736]
 [175.32167]
 [167.51408]
 [148.76749]
 [190.72131]]
398 Cost :  7.1930027 
 Prediction : 
 [[151.70811 ]
 [185.2398  ]
 [180.94019 ]
 [198.92422 ]
 [140.30487 ]
 [106.361084]
 [150.63315 ]
 [114.07484 ]
 [175.91737 ]
 [167.12424 ]
 [144.0708  ]
 [143.9557  ]
 [185.15897 ]
 [151.40526 ]
 [151.9404  ]
 [189.45038 ]
 [142.824

490 Cost :  7.0993595 
 Prediction : 
 [[151.75365]
 [185.21939]
 [180.96042]
 [198.92656]
 [140.28688]
 [106.30855]
 [150.6266 ]
 [114.06065]
 [175.85677]
 [167.01776]
 [144.06236]
 [143.90663]
 [185.19873]
 [151.46143]
 [151.92043]
 [189.4178 ]
 [142.87859]
 [181.4139 ]
 [175.83057]
 [157.28578]
 [176.50584]
 [175.2877 ]
 [167.5152 ]
 [148.85866]
 [190.72124]]
491 Cost :  7.0983796 
 Prediction : 
 [[151.75414]
 [185.21916]
 [180.96063]
 [198.92659]
 [140.28668]
 [106.30799]
 [150.62654]
 [114.0605 ]
 [175.85611]
 [167.01662]
 [144.06227]
 [143.90611]
 [185.19914]
 [151.46202]
 [151.92021]
 [189.41747]
 [142.87917]
 [181.41386]
 [175.83113]
 [157.28632]
 [176.50572]
 [175.28735]
 [167.51521]
 [148.85962]
 [190.72124]]
492 Cost :  7.097404 
 Prediction : 
 [[151.75461]
 [185.21895]
 [180.96085]
 [198.92659]
 [140.28648]
 [106.30742]
 [150.62646]
 [114.06034]
 [175.85545]
 [167.01549]
 [144.06218]
 [143.90558]
 [185.19957]
 [151.46262]
 [151.92   ]
 [189.4171 ]
 [142.87975]
 [181.41382

629 Cost :  6.9715486 
 Prediction : 
 [[151.81906 ]
 [185.18999 ]
 [180.98944 ]
 [198.9299  ]
 [140.26086 ]
 [106.233055]
 [150.61732 ]
 [114.040504]
 [175.76962 ]
 [166.86484 ]
 [144.05023 ]
 [143.83614 ]
 [185.25577 ]
 [151.54196 ]
 [151.89182 ]
 [189.371   ]
 [142.95609 ]
 [181.40997 ]
 [175.9061  ]
 [157.3599  ]
 [176.48953 ]
 [175.23941 ]
 [167.51688 ]
 [148.9881  ]
 [190.72104 ]]
630 Cost :  6.97069 
 Prediction : 
 [[151.81952]
 [185.18979]
 [180.98965]
 [198.92993]
 [140.2607 ]
 [106.23253]
 [150.61726]
 [114.04037]
 [175.76903]
 [166.86378]
 [144.05016]
 [143.83566]
 [185.25616]
 [151.54254]
 [151.89163]
 [189.37068]
 [142.95663]
 [181.40996]
 [175.90662]
 [157.36041]
 [176.48943]
 [175.23909]
 [167.51689]
 [148.989  ]
 [190.72107]]
631 Cost :  6.969836 
 Prediction : 
 [[151.81999]
 [185.18958]
 [180.98987]
 [198.92996]
 [140.26051]
 [106.232  ]
 [150.6172 ]
 [114.04022]
 [175.76842]
 [166.86272]
 [144.05008]
 [143.83517]
 [185.25658]
 [151.54309]
 [151.89143]
 [189.37036]
 

735 Cost :  6.884145 
 Prediction : 
 [[151.8664 ]
 [185.1687 ]
 [181.01044]
 [198.93237]
 [140.242  ]
 [106.17847]
 [150.61075]
 [114.02614]
 [175.70665]
 [166.75443]
 [144.04153]
 [143.78523]
 [185.29697]
 [151.60008]
 [151.87128]
 [189.33719]
 [143.01193]
 [181.40735]
 [175.96063]
 [157.41344]
 [176.47787]
 [175.20453]
 [167.51819]
 [149.08157]
 [190.72087]]
736 Cost :  6.883357 
 Prediction : 
 [[151.86682]
 [185.1685 ]
 [181.01065]
 [198.9324 ]
 [140.24182]
 [106.17797]
 [150.61067]
 [114.02601]
 [175.70609]
 [166.7534 ]
 [144.04144]
 [143.78476]
 [185.29735]
 [151.60062]
 [151.8711 ]
 [189.33688]
 [143.01245]
 [181.40732]
 [175.96115]
 [157.41393]
 [176.47778]
 [175.20422]
 [167.5182 ]
 [149.08244]
 [190.72087]]
737 Cost :  6.882568 
 Prediction : 
 [[151.86726]
 [185.1683 ]
 [181.01083]
 [198.93243]
 [140.24165]
 [106.17747]
 [150.61063]
 [114.02588]
 [175.7055 ]
 [166.75238]
 [144.04137]
 [143.78429]
 [185.29773]
 [151.60117]
 [151.87088]
 [189.33658]
 [143.01295]
 [181.40729]


828 Cost :  6.8139253 
 Prediction : 
 [[151.90614]
 [185.15077]
 [181.02806]
 [198.93446]
 [140.22606]
 [106.13261]
 [150.60526]
 [114.0142 ]
 [175.65373]
 [166.66168]
 [144.03423]
 [143.74245]
 [185.33151]
 [151.6488 ]
 [151.85405]
 [189.30876]
 [143.0587 ]
 [181.40523]
 [176.0064 ]
 [157.45839]
 [176.46812]
 [175.17522]
 [167.51933]
 [149.16003]
 [190.72066]]
829 Cost :  6.813189 
 Prediction : 
 [[151.90656 ]
 [185.15057 ]
 [181.02824 ]
 [198.9345  ]
 [140.2259  ]
 [106.132126]
 [150.60521 ]
 [114.014084]
 [175.65317 ]
 [166.6607  ]
 [144.03413 ]
 [143.742   ]
 [185.33188 ]
 [151.64932 ]
 [151.85387 ]
 [189.30846 ]
 [143.05919 ]
 [181.40521 ]
 [176.00688 ]
 [157.45886 ]
 [176.46803 ]
 [175.17491 ]
 [167.51936 ]
 [149.16087 ]
 [190.72066 ]]
830 Cost :  6.8124804 
 Prediction : 
 [[151.90698 ]
 [185.15039 ]
 [181.02843 ]
 [198.93452 ]
 [140.22574 ]
 [106.131645]
 [150.60515 ]
 [114.01396 ]
 [175.65262 ]
 [166.65973 ]
 [144.03407 ]
 [143.74155 ]
 [185.33224 ]
 [151.64983 ]
 [151.8537 

 [190.7203 ]]
960 Cost :  6.723677 
 Prediction : 
 [[151.95987 ]
 [185.12646 ]
 [181.05185 ]
 [198.93729 ]
 [140.20442 ]
 [106.0706  ]
 [150.59796 ]
 [113.998276]
 [175.58218 ]
 [166.53644 ]
 [144.02438 ]
 [143.68466 ]
 [185.37813 ]
 [151.71452 ]
 [151.83089 ]
 [189.27034 ]
 [143.12167 ]
 [181.40256 ]
 [176.0682  ]
 [157.51909 ]
 [176.45505 ]
 [175.13559 ]
 [167.52098 ]
 [149.26598 ]
 [190.7203  ]]
961 Cost :  6.723023 
 Prediction : 
 [[151.96027 ]
 [185.12628 ]
 [181.052   ]
 [198.93732 ]
 [140.20428 ]
 [106.070145]
 [150.59792 ]
 [113.99817 ]
 [175.58167 ]
 [166.5355  ]
 [144.0243  ]
 [143.68423 ]
 [185.37848 ]
 [151.715   ]
 [151.83072 ]
 [189.27005 ]
 [143.12215 ]
 [181.40254 ]
 [176.06866 ]
 [157.51955 ]
 [176.45496 ]
 [175.13528 ]
 [167.521   ]
 [149.26675 ]
 [190.7203  ]]
962 Cost :  6.7223797 
 Prediction : 
 [[151.96066 ]
 [185.1261  ]
 [181.05219 ]
 [198.93735 ]
 [140.20412 ]
 [106.069695]
 [150.59787 ]
 [113.998055]
 [175.58113 ]
 [166.53459 ]
 [144.02423 ]
 [143.6838  ]
 

1099 Cost :  6.639372 
 Prediction : 
 [[152.01323]
 [185.10226]
 [181.07541]
 [198.94012]
 [140.18282]
 [106.00904]
 [150.59085]
 [113.98274]
 [175.51114]
 [166.4122 ]
 [144.01463]
 [143.62729]
 [185.42432]
 [151.77957]
 [151.80801]
 [189.23218]
 [143.18394]
 [181.40012]
 [176.12946]
 [157.57932]
 [176.4422 ]
 [175.09624]
 [167.5227 ]
 [149.37102]
 [190.71986]]
1100 Cost :  6.638794 
 Prediction : 
 [[152.01361 ]
 [185.10211 ]
 [181.07558 ]
 [198.94017 ]
 [140.18268 ]
 [106.008606]
 [150.59082 ]
 [113.98263 ]
 [175.51065 ]
 [166.41135 ]
 [144.01457 ]
 [143.6269  ]
 [185.42464 ]
 [151.78004 ]
 [151.80786 ]
 [189.23193 ]
 [143.18439 ]
 [181.40012 ]
 [176.12988 ]
 [157.57974 ]
 [176.44211 ]
 [175.09596 ]
 [167.52274 ]
 [149.37175 ]
 [190.71988 ]]
1101 Cost :  6.6382246 
 Prediction : 
 [[152.01398]
 [185.10194]
 [181.07574]
 [198.94019]
 [140.18253]
 [106.00818]
 [150.59076]
 [113.98252]
 [175.51016]
 [166.41048]
 [144.0145 ]
 [143.6265 ]
 [185.42496]
 [151.78049]
 [151.80771]
 [189.2316

1223 Cost :  6.572438 
 Prediction : 
 [[152.05821]
 [185.08185]
 [181.09525]
 [198.94257]
 [140.16452]
 [105.95716]
 [150.58499]
 [113.96987]
 [175.4513 ]
 [166.30765]
 [144.00648]
 [143.57901]
 [185.46317]
 [151.83426]
 [151.78888]
 [189.20004]
 [143.2362 ]
 [181.39825]
 [176.181  ]
 [157.62999]
 [176.43149]
 [175.06308]
 [167.52428]
 [149.4594 ]
 [190.71942]]
1224 Cost :  6.5719185 
 Prediction : 
 [[152.05856]
 [185.08168]
 [181.0954 ]
 [198.94258]
 [140.16437]
 [105.95675]
 [150.58495]
 [113.96976]
 [175.45082]
 [166.30682]
 [144.00641]
 [143.57863]
 [185.46347]
 [151.83469]
 [151.78873]
 [189.1998 ]
 [143.2366 ]
 [181.39825]
 [176.18141]
 [157.6304 ]
 [176.4314 ]
 [175.06284]
 [167.52429]
 [149.4601 ]
 [190.71942]]
1225 Cost :  6.571402 
 Prediction : 
 [[152.05893 ]
 [185.08154 ]
 [181.09558 ]
 [198.94263 ]
 [140.16423 ]
 [105.956345]
 [150.5849  ]
 [113.969666]
 [175.45036 ]
 [166.30603 ]
 [144.00636 ]
 [143.57825 ]
 [185.46378 ]
 [151.83514 ]
 [151.78857 ]
 [189.19955 ]
 [143.

1348 Cost :  6.511981 
 Prediction : 
 [[152.10118]
 [185.06229]
 [181.11418]
 [198.94492]
 [140.14694]
 [105.9076 ]
 [150.5795 ]
 [113.95776]
 [175.39413]
 [166.2079 ]
 [143.99873]
 [143.53291]
 [185.50018]
 [151.88637]
 [151.77069]
 [189.16936]
 [143.2859 ]
 [181.39668]
 [176.23018]
 [157.67836]
 [176.42136]
 [175.03145]
 [167.52586]
 [149.54372]
 [190.71896]]
1349 Cost :  6.511526 
 Prediction : 
 [[152.1015 ]
 [185.06213]
 [181.11432]
 [198.94492]
 [140.14679]
 [105.90722]
 [150.57944]
 [113.95768]
 [175.39368]
 [166.20712]
 [143.99866]
 [143.53255]
 [185.50046]
 [151.88675]
 [151.77054]
 [189.1691 ]
 [143.28627]
 [181.39664]
 [176.23055]
 [157.67873]
 [176.42126]
 [175.03119]
 [167.52588]
 [149.54436]
 [190.71893]]
1350 Cost :  6.51108 
 Prediction : 
 [[152.10184 ]
 [185.06198 ]
 [181.11447 ]
 [198.94495 ]
 [140.14667 ]
 [105.906845]
 [150.5794  ]
 [113.95759 ]
 [175.39325 ]
 [166.20634 ]
 [143.9986  ]
 [143.5322  ]
 [185.50075 ]
 [151.88716 ]
 [151.7704  ]
 [189.16887 ]
 [143.28

1490 Cost :  6.4509473 
 Prediction : 
 [[152.14723]
 [185.04124]
 [181.13445]
 [198.94745]
 [140.12798]
 [105.85447]
 [150.57372]
 [113.94504]
 [175.33284]
 [166.10106]
 [143.99045]
 [143.4835 ]
 [185.53978]
 [151.94205]
 [151.7513 ]
 [189.13643]
 [143.33891]
 [181.39516]
 [176.2828 ]
 [157.73015]
 [176.4106 ]
 [174.99751]
 [167.52766]
 [149.63396]
 [190.71837]]
1491 Cost :  6.450551 
 Prediction : 
 [[152.14755 ]
 [185.04109 ]
 [181.1346  ]
 [198.94746 ]
 [140.12785 ]
 [105.85411 ]
 [150.57368 ]
 [113.944954]
 [175.33241 ]
 [166.10033 ]
 [143.99039 ]
 [143.48317 ]
 [185.54005 ]
 [151.94243 ]
 [151.75117 ]
 [189.13622 ]
 [143.33928 ]
 [181.39514 ]
 [176.28316 ]
 [157.73051 ]
 [176.41054 ]
 [174.99728 ]
 [167.52766 ]
 [149.63458 ]
 [190.71837 ]]
1492 Cost :  6.450144 
 Prediction : 
 [[152.14787]
 [185.04097]
 [181.13475]
 [198.9475 ]
 [140.12773]
 [105.85375]
 [150.57365]
 [113.94487]
 [175.33202]
 [166.09961]
 [143.99034]
 [143.48283]
 [185.54033]
 [151.9428 ]
 [151.75105]
 [189.136 

1621 Cost :  6.401043 
 Prediction : 
 [[152.1873 ]
 [185.0229 ]
 [181.15205]
 [198.94969]
 [140.11139]
 [105.80825]
 [150.5688 ]
 [113.93417]
 [175.27953]
 [166.00826]
 [143.98329]
 [143.44058]
 [185.57414]
 [151.99031]
 [151.73456]
 [189.10783]
 [143.38481]
 [181.39403]
 [176.32849]
 [157.77513]
 [176.40135]
 [174.968  ]
 [167.52931]
 [149.71233]
 [190.71777]]
1622 Cost :  6.400694 
 Prediction : 
 [[152.18759 ]
 [185.02275 ]
 [181.15218 ]
 [198.9497  ]
 [140.11125 ]
 [105.807915]
 [150.56877 ]
 [113.9341  ]
 [175.27913 ]
 [166.00757 ]
 [143.98323 ]
 [143.44026 ]
 [185.57439 ]
 [151.99066 ]
 [151.73442 ]
 [189.10762 ]
 [143.38515 ]
 [181.394   ]
 [176.32881 ]
 [157.77547 ]
 [176.40129 ]
 [174.96779 ]
 [167.52931 ]
 [149.7129  ]
 [190.71776 ]]
1623 Cost :  6.400338 
 Prediction : 
 [[152.18787]
 [185.02261]
 [181.15231]
 [198.9497 ]
 [140.11113]
 [105.80757]
 [150.56873]
 [113.93402]
 [175.27875]
 [166.00687]
 [143.98315]
 [143.43994]
 [185.57465]
 [151.99101]
 [151.7343 ]
 [189.10739

1700 Cost :  6.3736415 
 Prediction : 
 [[152.21039]
 [185.0123 ]
 [181.16217]
 [198.95097]
 [140.10178]
 [105.78163]
 [150.56602]
 [113.92802]
 [175.24881]
 [165.95483]
 [143.97916]
 [143.41586]
 [185.59389]
 [152.01805]
 [151.72495]
 [189.09134]
 [143.41113]
 [181.39345]
 [176.35477]
 [157.80103]
 [176.39607]
 [174.951  ]
 [167.53027]
 [149.75742]
 [190.7174 ]]
1701 Cost :  6.373293 
 Prediction : 
 [[152.21066 ]
 [185.01218 ]
 [181.1623  ]
 [198.95099 ]
 [140.10165 ]
 [105.781296]
 [150.56598 ]
 [113.92794 ]
 [175.24844 ]
 [165.95416 ]
 [143.9791  ]
 [143.41554 ]
 [185.59413 ]
 [152.01839 ]
 [151.72484 ]
 [189.09113 ]
 [143.41147 ]
 [181.39343 ]
 [176.3551  ]
 [157.80135 ]
 [176.396   ]
 [174.95079 ]
 [167.5303  ]
 [149.75798 ]
 [190.71738 ]]
1702 Cost :  6.3729777 
 Prediction : 
 [[152.21097]
 [185.01204]
 [181.16245]
 [198.95102]
 [140.10153]
 [105.78097]
 [150.56596]
 [113.92787]
 [175.24806]
 [165.9535 ]
 [143.97906]
 [143.41525]
 [185.59439]
 [152.01874]
 [151.72472]
 [189.090

 [190.71704]]
1772 Cost :  6.350257 
 Prediction : 
 [[152.23074 ]
 [185.00293 ]
 [181.17111 ]
 [198.95212 ]
 [140.09326 ]
 [105.75814 ]
 [150.5636  ]
 [113.922646]
 [175.22173 ]
 [165.90773 ]
 [143.97554 ]
 [143.39404 ]
 [185.6113  ]
 [152.04248 ]
 [151.71652 ]
 [189.07678 ]
 [143.43431 ]
 [181.39299 ]
 [176.37794 ]
 [157.82385 ]
 [176.39145 ]
 [174.936   ]
 [167.53119 ]
 [149.79715 ]
 [190.71704 ]]
1773 Cost :  6.349953 
 Prediction : 
 [[152.23102]
 [185.0028 ]
 [181.17123]
 [198.95215]
 [140.09315]
 [105.75782]
 [150.56357]
 [113.92258]
 [175.22134]
 [165.90709]
 [143.9755 ]
 [143.39375]
 [185.61154]
 [152.04282]
 [151.7164 ]
 [189.07658]
 [143.43463]
 [181.39299]
 [176.37827]
 [157.82416]
 [176.39139]
 [174.9358 ]
 [167.53119]
 [149.79771]
 [190.71704]]
1774 Cost :  6.3496294 
 Prediction : 
 [[152.23131]
 [185.00269]
 [181.17136]
 [198.95216]
 [140.09305]
 [105.7575 ]
 [150.56354]
 [113.92251]
 [175.22098]
 [165.90645]
 [143.97545]
 [143.39346]
 [185.61179]
 [152.04315]
 [151.716

1899 Cost :  6.312486 
 Prediction : 
 [[152.26518 ]
 [184.98709 ]
 [181.18617 ]
 [198.9541  ]
 [140.07884 ]
 [105.718445]
 [150.55959 ]
 [113.91372 ]
 [175.17595 ]
 [165.82823 ]
 [143.96945 ]
 [143.35724 ]
 [185.64067 ]
 [152.08368 ]
 [151.70233 ]
 [189.05222 ]
 [143.47331 ]
 [181.39236 ]
 [176.41705 ]
 [157.8624  ]
 [176.3837  ]
 [174.91068 ]
 [167.53276 ]
 [149.86424 ]
 [190.71642 ]]
1900 Cost :  6.3121963 
 Prediction : 
 [[152.26544]
 [184.98695]
 [181.1863 ]
 [198.95412]
 [140.07874]
 [105.71815]
 [150.55957]
 [113.91365]
 [175.1756 ]
 [165.82762]
 [143.9694 ]
 [143.35695]
 [185.6409 ]
 [152.084  ]
 [151.70222]
 [189.05203]
 [143.47362]
 [181.39235]
 [176.41734]
 [157.86269]
 [176.38365]
 [174.9105 ]
 [167.53279]
 [149.86476]
 [190.71642]]
1901 Cost :  6.311931 
 Prediction : 
 [[152.2657  ]
 [184.98686 ]
 [181.18642 ]
 [198.95415 ]
 [140.07863 ]
 [105.717834]
 [150.55954 ]
 [113.91358 ]
 [175.17525 ]
 [165.82703 ]
 [143.96938 ]
 [143.35667 ]
 [185.64113 ]
 [152.08432 ]
 [151.702

In [28]:
# Ask my Score
print("Your score will be ", sess.run(hypothesis, feed_dict={X:[[100, 70, 101]]}))

Your score will be  [[189.25562]]


In [29]:
print("Your score will be ", sess.run(hypothesis, feed_dict={X:[[60, 70, 110], [90, 100, 80]]}))

Your score will be  [[185.2088]
 [173.5013]]


# Batch

In [31]:
filename_queue = tf.train.string_input_producer(['data-01-test-score.csv'], shuffle=False, name = 'filename_queue')

Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(string_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(input_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensors(tensor).repeat(num_epochs)`.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.


In [32]:
reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.TextLineDataset`.


In [33]:
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

In [36]:
train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size = 10)

Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.batch(batch_size)` (or `padded_batch(...)` if `dynamic_pad=True`).


In [37]:
X = tf.placeholder(tf.float32, shape=[None,3])
Y = tf.placeholder(tf.float32, shape=[None,1])

In [38]:
W = tf.Variable(tf.random_normal([3,1]), name = 'Weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

In [39]:
hypothesis = tf.matmul(X,W) + b 

In [40]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [41]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [51]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [52]:
coord = tf.train.Coordinator()

In [53]:
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

In [54]:
for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    print("x_batch \n",x_batch, "Y_batch \n",y_batch)
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X:x_batch, Y:y_batch})
    
    if step % 10 == 0:
        print(stop, "Cost : ", cost_val, "\n Prediction : \n", hy_val)
        
coord.request_stop()
coord.join(threads)

x_batch 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] Y_batch 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
0 Cost :  20858.195 
 Prediction : 
 [[21.191814]
 [15.67258 ]
 [20.678411]
 [21.135958]
 [10.497708]
 [ 4.138444]
 [16.265074]
 [13.043258]
 [10.515986]
 [ 5.586463]]
x_batch 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] Y_batch 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] Y_batch 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch 
 [[53. 

x_batch 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] Y_batch 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
x_batch 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] Y_batch 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] Y_batch 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] Y_batch 
 [[101.]
 [149

 [ 73.  66.  70.]] Y_batch 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] Y_batch 
 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] Y_batch 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] Y_batch 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
0 Cost :  41.647385 
 Prediction : 
 [[159.09494]
 [181.76633]
 [184.14682]
 [199.25911]
 [137.1802 ]
 [

 [ 73.  66.  70.]] Y_batch 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] Y_batch 
 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] Y_batch 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] Y_batch 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
x_batch 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78

 [ 79.  70.  88.]] Y_batch 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
0 Cost :  39.23852 
 Prediction : 
 [[158.91939]
 [181.86568]
 [184.07777]
 [199.26932]
 [137.26265]
 [ 97.95008]
 [149.68593]
 [112.04827]
 [166.20645]
 [150.24818]]
x_batch 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] Y_batch 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] Y_batch 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] Y_batch 
 [[101.]
 [149.]
 [

 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] Y_batch 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] Y_batch 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
0 Cost :  37.93094 
 Prediction : 
 [[158.82155]
 [181.92107]
 [184.0393 ]
 [199.27498]
 [137.30865]
 [ 98.07758]
 [149.71234]
 [112.09374]
 [166.35646]
 [150.50775]]
x_batch 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] Y_batch 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83

x_batch 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] Y_batch 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] Y_batch 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
x_batch 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] Y_batch 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] Y_batch 
 [[177.]
 [175

 [96. 93. 95.]] Y_batch 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] Y_batch 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
0 Cost :  35.161293 
 Prediction : 
 [[158.60768]
 [182.04218]
 [183.95526]
 [199.28728]
 [137.4093 ]
 [ 98.35621]
 [149.76987]
 [112.19274]
 [166.68425]
 [151.0747 ]]
x_batch 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] Y_batch 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] 

 [96. 93. 95.]] Y_batch 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] Y_batch 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
x_batch 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] Y_batch 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] Y_batch 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 7

 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] Y_batch 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] Y_batch 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
x_batch 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] Y_batch 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] Y_batch 
 [[177.]
 [175.]
 [175.

x_batch 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] Y_batch 
 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] Y_batch 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] Y_batch 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
x_batch 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] Y_batch 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [1

 [70. 73. 78.]] Y_batch 
 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] Y_batch 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] Y_batch 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
0 Cost :  30.776913 
 Prediction : 
 [[158.24825]
 [182.24599]
 [183.81413]
 [199.30788]
 [137.57895]
 [ 98.82444]
 [149.86598]
 [112.35807]
 [167.23512]
 [152.02701]]
x_batch 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] Y_batch 
 [[141.]
 [141.]
 [18

 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] Y_batch 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] Y_batch 
 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] Y_batch 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] Y_batch 
 [[152.]
 [185.]
 [180.

0 Cost :  28.818676 
 Prediction : 
 [[158.078  ]
 [182.34264]
 [183.74736]
 [199.31755]
 [137.65953]
 [ 99.04619]
 [149.91124]
 [112.43585]
 [167.49602]
 [152.47775]]
x_batch 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] Y_batch 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] Y_batch 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] Y_batch 
 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 

x_batch 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] Y_batch 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] Y_batch 
 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] Y_batch 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] Y_batch 
 [[152.]
 [185

x_batch 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] Y_batch 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] Y_batch 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
0 Cost :  26.784021 
 Prediction : 
 [[157.89368]
 [182.44737]
 [183.6751 ]
 [199.32802]
 [137.74695]
 [ 99.28628]
 [149.96005]
 [112.51968]
 [167.7785 ]
 [152.9656 ]]
x_batch 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] Y_batch 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]


x_batch 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] Y_batch 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
x_batch 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] Y_batch 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] Y_batch 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] Y_batch 
 [[101.]
 [149

 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] Y_batch 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] Y_batch 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
0 Cost :  24.913994 
 Prediction : 
 [[157.71663]
 [182.54803]
 [183.60574]
 [199.33798]
 [137.83104]
 [ 99.51682]
 [150.00668]
 [112.59976]
 [168.04974]
 [153.43384]]
x_batch 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] Y_batch 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  8

x_batch 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] Y_batch 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
x_batch 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] Y_batch 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] Y_batch 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] Y_batch 
 [[101.]
 [149

 [96. 93. 95.]] Y_batch 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] Y_batch 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
0 Cost :  23.564816 
 Prediction : 
 [[157.5838 ]
 [182.62363]
 [183.55376]
 [199.34546]
 [137.89427]
 [ 99.68978]
 [150.04155]
 [112.65958]
 [168.25325]
 [153.785  ]]
x_batch 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] Y_batch 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] 

x_batch 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] Y_batch 
 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] Y_batch 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] Y_batch 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
0 Cost :  22.83273 
 Prediction : 
 [[157.50975]
 [182.66579]
 [183.52477]
 [199.34958]
 [137.92958]
 [ 99.7862 ]
 [150.06091]
 [112.69282]
 [168.36667]
 [153.9807 ]]
x_batch 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 9

 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] Y_batch 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
0 Cost :  22.127731 
 Prediction : 
 [[157.43704]
 [182.70721]
 [183.4963 ]
 [199.35365]
 [137.96426]
 [ 99.88089]
 [150.07991]
 [112.72538]
 [168.47809]
 [154.17285]]
x_batch 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] Y_batch 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] Y_batch 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch 
 [[53. 46. 55.]


x_batch 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] Y_batch 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
x_batch 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] Y_batch 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] Y_batch 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] Y_batch 
 [[101.]
 [149

0 Cost :  20.635193 
 Prediction : 
 [[157.2781 ]
 [182.79782]
 [183.4342 ]
 [199.3625 ]
 [138.0402 ]
 [100.08781]
 [150.12125]
 [112.79626]
 [168.72153]
 [154.59262]]
x_batch 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] Y_batch 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] Y_batch 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] Y_batch 
 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 

 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] Y_batch 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] Y_batch 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
x_batch 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] Y_batch 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] Y_batch 
 [[177.]
 [175.]
 [175.

 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] Y_batch 
 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] Y_batch 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] Y_batch 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
0 Cost :  19.2639 
 Prediction : 
 [[157.12546]
 [182.88489]
 [183.37457]
 [199.37094]
 [138.1133 ]
 [100.28649]
 [150.16075]
 [112.86394]
 [168.95532]
 [154.99554]]
x_batch 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [

 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] Y_batch 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] Y_batch 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
0 Cost :  18.832062 
 Prediction : 
 [[157.07596]
 [182.91318]
 [183.35524]
 [199.37367]
 [138.13705]
 [100.35096]
 [150.17354]
 [112.88582]
 [169.03117]
 [155.12624]]
x_batch 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] Y_batch 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  8

 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] Y_batch 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
x_batch 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] Y_batch 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] Y_batch 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] Y_batch 
 [[101.]
 [149.]
 [115.

 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] Y_batch 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] Y_batch 
 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] Y_batch 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] Y_batch 
 [[152.]
 [185.]
 [180.

 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] Y_batch 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] Y_batch 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
x_batch 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] Y_batch 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] Y_batch 
 [[177.]
 [175.]
 [175.

 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] Y_batch 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] Y_batch 
 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] Y_batch 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] Y_batch 
 [[152.]
 [185.]
 [180.

 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] Y_batch 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] Y_batch 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] Y_batch 
 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] Y_batch 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [17

x_batch 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] Y_batch 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] Y_batch 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] Y_batch 
 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] Y_batch 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [1

 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] Y_batch 
 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] Y_batch 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] Y_batch 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
x_batch 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] Y_batch 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [14

x_batch 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] Y_batch 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
0 Cost :  14.603503 
 Prediction : 
 [[156.54486]
 [183.21701]
 [183.14825]
 [199.40266]
 [138.39297]
 [101.04211]
 [150.30907]
 [113.1176 ]
 [169.84442]
 [156.52597]]
x_batch 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] Y_batch 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] Y_batch 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch 
 [[53. 

 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] Y_batch 
 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] Y_batch 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] Y_batch 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
x_batch 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] Y_batch 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [14

x_batch 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] Y_batch 
 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] Y_batch 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] Y_batch 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
x_batch 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] Y_batch 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [1

 [192.]]
x_batch 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] Y_batch 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
x_batch 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] Y_batch 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] Y_batch 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] Y_batch 
 [[10

 [192.]]
x_batch 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] Y_batch 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
x_batch 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] Y_batch 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] Y_batch 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] Y_batch 
 [[10

 [192.]]
x_batch 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] Y_batch 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
x_batch 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] Y_batch 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] Y_batch 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] Y_batch 
 [[10

x_batch 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] Y_batch 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] Y_batch 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] Y_batch 
 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] Y_batch 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [1

 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] Y_batch 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] Y_batch 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
0 Cost :  12.099497 
 Prediction : 
 [[156.1761 ]
 [183.42873]
 [183.00496]
 [199.42238]
 [138.57214]
 [101.52182]
 [150.40132]
 [113.27501]
 [170.40892]
 [157.49585]]
x_batch 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] Y_batch 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192

 [70. 73. 78.]] Y_batch 
 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] Y_batch 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] Y_batch 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
x_batch 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] Y_batch 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73. 

 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] Y_batch 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
x_batch 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] Y_batch 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] Y_batch 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] Y_batch 
 [[101.]
 [149.]
 [115.

 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] Y_batch 
 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] Y_batch 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] Y_batch 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
x_batch 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [

x_batch 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] Y_batch 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] Y_batch 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] Y_batch 
 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] Y_batch 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [1

 [70. 73. 78.]] Y_batch 
 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] Y_batch 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] Y_batch 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
0 Cost :  10.679623 
 Prediction : 
 [[155.93962 ]
 [183.5649  ]
 [182.9133  ]
 [199.43483 ]
 [138.6878  ]
 [101.829346]
 [150.45955 ]
 [113.374146]
 [170.77083 ]
 [158.11674 ]]
x_batch 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] Y_batch 
 [[141.]
 [

 [159.]]
x_batch 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] Y_batch 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] Y_batch 
 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] Y_batch 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] Y_batch 
 [[15

x_batch 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] Y_batch 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] Y_batch 
 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] Y_batch 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] Y_batch 
 [[152.]
 [185

x_batch 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] Y_batch 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] Y_batch 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] Y_batch 
 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] Y_batch 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [1