In [1]:
import numpy as np
import tensorflow as tf

In [2]:
xy = np.loadtxt("data-04-zoo.csv", delimiter=',', dtype=np.float32)

In [5]:
x_data = xy[:,0:-1]
y_data = xy[:,[-1]]

In [8]:
print(x_data)
print(y_data)

[[1. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 1. 0. 1.]
 [0. 0. 1. ... 1. 0. 0.]
 ...
 [1. 0. 0. ... 1. 0. 1.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 1. 0. 0.]]
[[0.]
 [0.]
 [3.]
 [0.]
 [0.]
 [0.]
 [0.]
 [3.]
 [3.]
 [0.]
 [0.]
 [1.]
 [3.]
 [6.]
 [6.]
 [6.]
 [1.]
 [0.]
 [3.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [5.]
 [4.]
 [4.]
 [0.]
 [0.]
 [0.]
 [5.]
 [0.]
 [0.]
 [1.]
 [3.]
 [0.]
 [0.]
 [1.]
 [3.]
 [5.]
 [5.]
 [1.]
 [5.]
 [1.]
 [0.]
 [0.]
 [6.]
 [0.]
 [0.]
 [0.]
 [0.]
 [5.]
 [4.]
 [6.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [3.]
 [3.]
 [2.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [6.]
 [3.]
 [0.]
 [0.]
 [2.]
 [6.]
 [1.]
 [1.]
 [2.]
 [6.]
 [3.]
 [1.]
 [0.]
 [6.]
 [3.]
 [1.]
 [5.]
 [4.]
 [2.]
 [2.]
 [3.]
 [0.]
 [0.]
 [1.]
 [0.]
 [5.]
 [0.]
 [6.]
 [1.]]


In [12]:
print(x_data.shape)
print(y_data.shape)

(101, 16)
(101, 1)


In [13]:
nb_classes = 7 # 0 ~ 6

In [14]:
X = tf.placeholder(tf.float32, [None, 16])
Y = tf.placeholder(tf.int32, [None, 1])

In [15]:
Y_one_hot = tf.one_hot(Y, nb_classes)
Y_one_hot = tf.reshape(Y_one_hot, [-1, nb_classes])

In [16]:
W = tf.Variable(tf.random_normal([16, nb_classes]), name = 'weight')
b = tf.Variable(tf.random_normal([nb_classes]), name = 'bias')

In [17]:
logits = tf.matmul(X, W) + b
hypothesis = tf.nn.softmax(logits)

In [18]:
cost_i = tf.nn.softmax_cross_entropy_with_logits(logits = logits, labels=Y_one_hot)

Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.



In [19]:
cost = tf.reduce_mean(cost_i)

In [20]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [21]:
prediction = tf.argmax(hypothesis, 1)
correct_prediction = tf.equal(prediction, tf.argmax(Y_one_hot, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

In [22]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(2000):
        sess.run(optimizer, feed_dict={X:x_data, Y:y_data})
        
        if step % 100 == 0:
            loss, acc = sess.run([cost, accuracy], feed_dict={X:x_data, Y:y_data})
            print("Step: {:5}\t Loss: {:.3f} \t Acc: {:.2%}".format(step, loss, acc))
            
    pred = sess.run(prediction, feed_dict={X:x_data})
    
    for p, y in zip(pred, y_data.flatten()):
        print("[{}] Prediction : {} True Y: {}".format(p == int(y), p, int(y)))

Step:     0	 Loss: 4.117 	 Acc: 37.62%
Step:   100	 Loss: 0.748 	 Acc: 74.26%
Step:   200	 Loss: 0.494 	 Acc: 82.18%
Step:   300	 Loss: 0.365 	 Acc: 86.14%
Step:   400	 Loss: 0.283 	 Acc: 91.09%
Step:   500	 Loss: 0.228 	 Acc: 95.05%
Step:   600	 Loss: 0.191 	 Acc: 97.03%
Step:   700	 Loss: 0.164 	 Acc: 98.02%
Step:   800	 Loss: 0.144 	 Acc: 98.02%
Step:   900	 Loss: 0.128 	 Acc: 98.02%
Step:  1000	 Loss: 0.115 	 Acc: 99.01%
Step:  1100	 Loss: 0.105 	 Acc: 99.01%
Step:  1200	 Loss: 0.096 	 Acc: 99.01%
Step:  1300	 Loss: 0.089 	 Acc: 99.01%
Step:  1400	 Loss: 0.082 	 Acc: 99.01%
Step:  1500	 Loss: 0.077 	 Acc: 99.01%
Step:  1600	 Loss: 0.072 	 Acc: 100.00%
Step:  1700	 Loss: 0.068 	 Acc: 100.00%
Step:  1800	 Loss: 0.064 	 Acc: 100.00%
Step:  1900	 Loss: 0.060 	 Acc: 100.00%
[True] Prediction : 0 True Y: 0
[True] Prediction : 0 True Y: 0
[True] Prediction : 3 True Y: 3
[True] Prediction : 0 True Y: 0
[True] Prediction : 0 True Y: 0
[True] Prediction : 0 True Y: 0
[True] Prediction : 0 Tr